FROM node:18-alpine
WORKDIR /app
RUN apk update && apk add --no-cache \
  autoconf \
  automake \
  g++ \
  libc6-compat \
  libjpeg-turbo-dev \
  libpng-dev \
  make \
  git \
  nasm

COPY example.env .env
COPY package.json package.json
COPY package-lock.json package-lock.json

COPY tsconfig.json tsconfig.json
COPY babel.config.js babel.config.js
COPY .eslintrc.js .eslintrc.js
COPY app.config.json app.config.json
COPY src src
COPY webpack webpack
COPY webpack.config.js webpack.config.js
RUN npm i
CMD npm run test-ci
